### ISSUE TITLE
Why firebase is there? - Documention

### ISSUE THREAD

**Issue by afzl-wtu** [mhmzdev/devfolio#10]
I do not understand why firebase files are there, may be some node modules too. I  have [read](https://itnext.io/folio-responsive-portfolio-using-flutter-2-0-86ae3e6cce4f) your article here too. But I could not find anywhere why firebase and node is inside the project.
Please forgive me if I am mistaken.

**Comment by mhmzdev** [comment]
The project is hosted on firebase, that's why firebase files are there and the node_modules are for firebase-cli npm package
