### ISSUE TITLE
Displays 404 not found when hosted

### ISSUE THREAD

**Issue by Hanzein** [mhmzdev/devfolio#21]
**After I recreate for my portofolio and finish it, Why when I host this web on vercel and github, it shows 404 not found, what's wrong?** 
![Screenshot 2024-06-12 at 02 43 18](https://github.com/mhmzdev/devfolio/assets/107041928/52c567b4-8450-4f5d-b178-94c0bd8c1fc1)

**Comment by mhmzdev** [comment]
This issue isn't related to the project but to the hosting. Hope you find the solution.
